export const GET_CHEAP = 'GET_CHEAP';
export const GET_CHEAP_SUCCESS = 'GET_CHEAP_SUCCESS';
export const GET_CHEAP_ERROR = 'GET_CHEAP_ERROR';
export const GET_CHEAP_LOADING = 'GET_CHEAP_LOADING';

export const GET_BUSINESS = 'GET_BUSINESS';
export const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';
export const GET_BUSINESS_ERROR = 'GET_BUSINESS_ERROR';
export const GET_BUSINESS_LOADING = 'GET_BUSINESS_LOADING';
